name: Testing GitHub WorkFlows using Configuration Variable

on:
 workflow_dispatch:

env:
  name: Lokesh

jobs:
  Greetings:
    runs-on: ubuntu-latest
    env:
      designation: DevOps Engineer
    steps:
      - name: Printing using Echo
        run: echo "I am $name. I live in $location and basically I am a $designation with ${{vars.exp}} experience"
        env:
          location: kerala
