name: Testing Variables in Github workflows
on :
  worflow_dispatch:
#globally declaring variables
env:
  NAME: Lokesh

jobs:
  Introduction_Job:
    runs-on : ubuntu-latest
    env:
      DESIGNATION: DevOps Engineer
    steps:
    - name: Printing the sentences
      run: echo "Iam $NAME, Iam $DESIGNATION and i live in $LOCATION"
      env:
        LOCATION: Bangalore
        
