name: Deploy Workflow with Inputs & Secrets

on:
  workflow_dispatch:

    inputs:
      env:
        description: 'Select environment to deploy to (dev, sit, uat, staging or prod)'
        required: true
        default: 'dev'
      version:
        description: 'App version to deploy'
        required: true
        default: 'latest'

jobs:
  Deploy_WorkFlow_Input_Secrets:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show inputs
        run: |
          echo "Env: ${{github.event.inputs.env}}"
          echo "Version: ${{ inputs.version }}"
      - name: Deploy to env
        env:
          API_Token: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          echo "Deploying version : ${{ inputs.version }} to ${{ inputs.env }}"
          echo  "Using secret token: ${{ secrets.API_TOKEN_GITHUB }}"
